# Automatically generated by nengo-bones, do not edit this file directly

# pylint: disable=consider-using-f-string,bad-string-format-type

"""
NengoOCL version information.

We use semantic versioning (see http://semver.org/) and conform to PEP440 (see
https://www.python.org/dev/peps/pep-0440/). '.dev0' will be added to the version
unless the code base represents a release version. Release versions are git
tagged with the version.
"""

version_info = (3, 0, 1)

name = "nengo-ocl"
dev = 0

# use old string formatting, so that this can still run in Python <= 3.5
# (since this file is parsed in setup.py, before python_requires is applied)
version = ".".join(str(v) for v in version_info)
if dev is not None:
    version += ".dev%d" % dev  # pragma: no cover

copyright = "Copyright (c) 2013-2023 Applied Brain Research"

bad_nengo_versions = [
    (2, 0, 0),
    (2, 0, 1),
    (2, 0, 2),
    (2, 0, 3),
    (2, 0, 4),
    (2, 1, 1),
    (2, 1, 2),
    (2, 2, 0),
    (2, 3, 0),
    (2, 3, 1),
    (2, 4, 0),
    (2, 5, 0),
    (2, 6, 0),
    (2, 7, 0),
    (2, 8, 0),
    (3, 0, 0),
]

# --- latest Nengo version at time of release
latest_nengo_version_info = (3, 1, 0)  # (major, minor, patch)
latest_nengo_version = ".".join(str(v) for v in latest_nengo_version_info)
